@startuml

start

while (есть еще пакеты?) is (да)

:Ожидание удовлетворительного уровня сигнала;
:Открытие TCP соединения;
if (Успешно?) then (ошибка)
    :Закрытие TCP соединения; 
    stop;
endif

:Отправка пакета авторизации;
if (ошибка?) then (ошибка) 
    :Закрытие TCP соединения; 
    stop;
endif

while (Есть еще пакеты данных?) is (да)
    :Чтение пакета из очереди;
    :Отправка пакета данных;
    if (ошибка?) then (ошибка) 
        :Закрытие TCP соединения; 
        stop;
    endif
    :Удаление пакета из очереди;
endwhile (нет)

:Отправка пакета завершения сессии;
if (ошибка?) then (ошибка) 
    break;
endif

endwhile (нет)

:Закрытие TCP соединения;

stop

@enduml
